### ISSUE TITLE
Magisk 7.1.2 says this is not a Magisk module

### ISSUE THREAD

**Issue by HJarausch** [TechnoSparks/encfs-magisk#1]
Hi
I've downloaded this repository as zip file and tried to install it by the Magisk Manager. 
But it says 'this is not a Magisk module' 
What am I missing? 
Many thanks for a hint
Helmut

**Comment by TechnoSparks** [comment]
Hello.

This module is still not updated to the latest version compatible with the Magisk v19 due to the template change. Until then, for now you will need to create a custom zip of your own or "hijack" another module's "system" folder, then proceed to copy the required binary files.

Onto the specifics of your issue, downloading the zip from github makes a nested folder like this:
```bash
encfs-magisk-master.zip
└── encfs-magisk-master
    ├── META-INF
    ├── arm64
    ├── arm
    └── [...]
```

Such folder structure will not make it recognisable as a Magisk module, therefore you will need to zip the "encfs-magisk-master" folder from inside ther parent zip. Use the resulting zipped file to install in Magisk Manager.

To save you the hassle, you can download the correct zip here as attached. However, I do not know if it would install for Magisk v19, but you can try anyway. Do report back the outcome.

[encfs-magisk.zip](https://github.com/TechnoSparks/encfs-magisk/files/3194121/encfs-magisk.zip)

**Comment by TechnoSparks** [comment]
Closing this issue as the OP didn't respond with the outcome
