### ISSUE TITLE
Installation finishes errorless, but there are no new binaries in /system/xbin

### ISSUE THREAD

**Issue by ethpi** [TechnoSparks/encfs-magisk#2]
Hi,

many thanks for your work. I tried to install encfs with magisk, but something went wrong. 

I used the ZIP-file in the issue #1 ( https://github.com/TechnoSparks/encfs-magisk/files/3194121/encfs-magisk.zip ). The installation works errorless, but after a reboot I can't find the binaries in /system/xbin. 

I remounted the root filesystem writable and to copied the binaries by hand to /system/xbin ... no good idea. After this braindead try Magisk didn't work correctly. 

I would very pleased, if anyone can tell me, how I can use the encfs binaries. I use LOS 18.1 on Samsung Galaxy S5 with Magisk 23.0.

**Comment by TechnoSparks** [comment]
The installer should be incompatible at this point in time. I don't know why Magisk didn't throw an error though! It also seems (I don't known since when) that Android no longer has `xbin` folder in `/system`. You can manually push the encfs files into system. Would you like me to walk you through that? In the meantime, please wait while I study what changes I need to make to this module. Expect an update soon

While I am going to address how to use EncFS using Magisk, I should also tip you that [Termux](https://f-droid.org/en/packages/com.termux/), with it's [root-repo](https://github.com/termux/termux-root-packages) installed, you can also easily run `pkg install encfs` and use it from within Termux. I personally think this is the best approach, especially considering that Termux also [have the ability to run scripts on boot](https://f-droid.org/en/packages/com.termux.boot/). A popular file explorer, [MiXplorer ](https://forum.xda-developers.com/t/app-2-2-mixplorer-v6-x-released-fully-featured-file-manager.1523691/) as has the ability to create and access (r/w) encfs directories.

**Comment by TechnoSparks** [comment]
> Hi,
> 
> many thanks for your work. I tried to install encfs with magisk, but something went wrong.
> 
> I used the ZIP-file in the issue #1 ( https://github.com/TechnoSparks/encfs-magisk/files/3194121/encfs-magisk.zip ). The installation works errorless, but after a reboot I can't find the binaries in /system/xbin.
> 
> I remounted the root filesystem writable and to copied the binaries by hand to /system/xbin ... no good idea. After this braindead try Magisk didn't work correctly.
> 
> I would very pleased, if anyone can tell me, how I can use the encfs binaries. I use LOS 18.1 on Samsung Galaxy S5 with Magisk 23.0.

The installer should be incompatible at this point in time. I don't know why Magisk didn't throw an error though! It also seems (I don't known since when) that Android no longer has `xbin` folder in `/system`. You can manually push the encfs files into system folder in `/data/adb/modules/<anymodules>`. Would you like me to walk you through that? In the meantime, please wait while I study what changes I need to make to this module. Expect an update soon

I should also tip you that [Termux](https://f-droid.org/en/packages/com.termux/), with it's [root-repo](https://github.com/termux/termux-root-packages) installed, you can also easily run `pkg install encfs` and use it from within Termux. I personally think this is the best approach, especially considering that Termux also [have the ability to run scripts on boot](https://f-droid.org/en/packages/com.termux.boot/). A popular file explorer, [MiXplorer ](https://forum.xda-developers.com/t/app-2-2-mixplorer-v6-x-released-fully-featured-file-manager.1523691/) also has the ability to create and access (r/w) encfs directories.

**Comment by ethpi** [comment]
My first attempt was Termux. It seems so easy, but if I use encfs as a normal user I get the error 

`fuse: failed to open /dev/fuse Permission denied`

If I use in Termux a cmdline like

`su -c /data/data/com.termux/files/usr/bin/bin/encfs /path1 /path2`

encfs runs errorless, but it seems that nothing happens:

`mount | grep path2 `

shows no mounted /path2. If I execute the command via root-adb, my device crashes and restarts. 

So I discarded Termux and tried Magisk. 

Is there an manual, how to use encfs with Termux so much that all apps can use the encrypted data?

**Comment by TechnoSparks** [comment]
I kinda want to help, but unfortunately, I am not well-versed in `encfs` anymore as my explorations with it was far long ago, and that I have since then moved on to `gocryptfs`. Simply put, I don't remember how to deal with `encfs` anymore 😔

>but if I use encfs as a normal user I get the error

`encfs` uses `FUSE`. However on android in order to use FUSE you will need root access.

> encfs runs errorless, but it seems that nothing happens:

This is because of namespace. To avoid future headache, set "Mount Namespace Mode" in Magisk settings to global. Otherwise you will need to modify your cmdline and add `-M` switch ie
```su -c -M /data/data/com.termux/files/usr/bin/bin/encfs /path1 /path2```
This is important, otherwise the changes you make to the `mount` won't reflect on other apps, even shell sessions! I think this should solve your issue in regards to encfs usage in Termux. **Do note** that this fact remains true even if you used my module.

> Is there an manual, how to use encfs with Termux so much that all apps can use the encrypted data?

If those apps require root, accessing the path is straightforward. However, if non-root apps like WhatsApp is involved, a lot of wizardry is required. [You may start from here](https://forum.xda-developers.com/t/mod-encrypt-sdcard-with-encfs.3027711/#post-75721227). Do be prepared as it will take you quite a little deep on how Android's sdcardfs functions. In summary, you will need to mount the encfs target with `allow_other` for it to work with non root, or `gid=9997,dmask=0007,fmask=0117,allow_other` should the mountpoint is in `/mnt/runtime/write/emulated/0/<mount_point>`.

**Comment by TechnoSparks** [comment]
I have published a release. Please let me know if it installs correctly by running `which encfs` in a root shell
https://github.com/TechnoSparks/encfs-magisk/releases/tag/v20220124

**Comment by TechnoSparks** [comment]
I tried myself, due to critical bugs, I have published a newer release. https://github.com/TechnoSparks/encfs-magisk/releases/tag/v1.0.1 I didn't test the functionality.

**Comment by ethpi** [comment]
v1.0.1 installs perfectly in LOS 18.1 with Magisk 23.0. A `which encfs` returns `/system/bin/encfs` as expected.

Many thanks for your work and advice in using Android's sdcardfs. For me the commandline

`encfs /mnt/runtime/write/1394-101B/encrypted/ /mnt/runtime/write/emulated/0/decrypted -- -o allow_other`

works properly. Now I can store my photos encrypted on my unencrypted SD-card (ID 1394-101B) and can access all them with a normal gallery app. In the next days I try to manage that this command will be executed on boot with Termux.

**Comment by TechnoSparks** [comment]
Nice, glad that it turned out working greatly for you!
